# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: SwiftDS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: |
          xcodebuild clean build \
            -project SwiftDS.xcodeproj \
            -scheme SwiftDS \
            -sdk iphonesimulator \
            -destination 'platform=iOS Simulator,name=iPhone 15,OS=18.2' \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
    - name: Run tests
      run: swift test -v
