# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: SwiftDS CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: xcodebuild  -scheme SwiftDS -project SwiftDS.xcodeproj -configuration Release destination 'platform=iOS Simulator,name=iPad (10th generation),OS=16.1' clean build 
    - name: Run tests
      run: swift test -v
